ITEM.name = "Dark Grenade"
ITEM.model = "models/items/grenadeammo.mdl"
ITEM.material = "models/combine_advisor/mask"
ITEM.desc = "A grenade that will temporarily prevent all light from entering an area."
ITEM.class = "tfa_flnade"
ITEM.uniqueID = "nut_darkgrenade"
ITEM.price = 0
ITEM.flag = "v"
ITEM.category = "Grenades"