ITEM.name = "Quest Enhancement"
ITEM.desc = "A custom enhancement item."
ITEM.uniqueID = "quest_enhance"
ITEM.model = "models/squad/sf_plates/sf_plate1x1.mdl"
ITEM.flag = "V"
ITEM.width = 1
ITEM.height = 1
ITEM.maxstack = 1
ITEM.upgradeLimit = 1
ITEM.combiner = true