ITEM.name = "Enhanced Backpack"
ITEM.desc = "Light as a feather, no matter what you put into it."
ITEM.width = 2
ITEM.height = 2
ITEM.invWidth = 5
ITEM.invHeight = 5
ITEM.category = "Storage"
ITEM.flag = "v"
ITEM.model = "models/warz/alicebackpack.mdl"
ITEM.material = "models/props_lab/security_screens"
ITEM.uniqueID = "pack_enhanced"