ITEM.name = "ALICE Pack"
ITEM.desc = "A reliable military backpack."
ITEM.width = 2
ITEM.height = 2
ITEM.invWidth = 4
ITEM.invHeight = 5
ITEM.category = "Storage"
ITEM.flag = "v"
ITEM.model = "models/warz/alicebackpack.mdl"
ITEM.uniqueID = "pack_alice"