ITEM.name = "Brief Case"
ITEM.desc = "A small bag that does not carry much."
ITEM.width = 2
ITEM.height = 2
ITEM.invWidth = 3
ITEM.invHeight = 3
ITEM.category = "Storage"
ITEM.flag = "v"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.uniqueID = "stor_briefcase"