ITEM.name = "Suture Kit"
ITEM.model = "models/props_lab/box01a.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.healAmount = 15
ITEM.healSeconds = 1
ITEM.price = 0
ITEM.desc = "A small box filled tools and sutures."
ITEM.uniqueID = "medical_suture"
ITEM.flag = "v"
ITEM.container = "j_empty_bandage"