ITEM.name = "Splint"
ITEM.model = "models/props_junk/wood_crate001a_chunk05.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.healAmount = 20
ITEM.healSeconds = 1
ITEM.price = 0
ITEM.desc = "A crude splint."
ITEM.uniqueID = "medical_splint"
ITEM.flag = "v"