ITEM.name = "Attuned Metal"
ITEM.desc = "A strange white metal that constantly emits a pleasant sound."
ITEM.uniqueID = "atunned_metal"
ITEM.model = "models/gibs/manhack_gib01.mdl"
ITEM.material = "models/props_pipes/destroyedpipes01a"
ITEM.flag = "j"
ITEM.width = 1
ITEM.height = 1
ITEM.maxstack = 10
ITEM.color = Color(30, 30, 30)