ITEM.name = "Platinum"
ITEM.desc = "A silvery-white metal useful in a variety of applications."
ITEM.uniqueID = "j_scrap_platinum"
ITEM.model = "models/gibs/shield_scanner_gib2.mdl"
ITEM.material = "phoenix_storms/trains/track_beamtop"
ITEM.flag = "j"
ITEM.width = 1
ITEM.height = 1
ITEM.maxstack = 10
ITEM.color = Color(160, 160, 160)