ITEM.name = "Haze of Blood"
ITEM.desc = "A mysterious book that holds important information."
ITEM.uniqueID = "story_blood_haze"
ITEM.model = "models/props_lab/binderbluelabel.mdl"
ITEM.price = 0
ITEM.flag = "3"
ITEM.material = "models/props_lab/security_screens2"
ITEM.contents = [[
		<p align="center"><font color='red' size='6'>Haze of Blood</font></p><br/>
		<font color='black' size='3'>
	The blood haze is a specific type of weather anomaly generally caused by the actions of Drifters.
		<br/><br/>
	The sky turns blood red, and a thick red fog fills the area. Visibility is extremely limited by the strangely shifting fog, and the situation is made worse by the increased presence and ferocity of Abominations, and occasionally Aberrations.The fog generated by blood haze seems to be made of a strange blood-like substance. It fills the area with the smell of blood, and in more severe cases can paint the entire ground and everyone outside in it as well. This appears to be the primary reason as to why Abominations become more fearsome and ravenous.
		<br/><br/>
	During events of blood haze, abominable cracks may open up on surfaces in the area. These cracks will almost always release a variety of abominations, and can remain open until the blood haze disperses.	
		<br/><br/>
	The underlying reason for most of the blood haze environmental reactions is the conflicting respite-altering consciousnesses of the Drifters in the Respite. However, it can also be caused by significant abomination presence as well. This is common in respite collisions (monoliths) and in times of brutal plastic warfare. In the case of other Respite altering consciousnesses, such as Ethereal Orbs, the reaction will not take place, as there their altering abilities are far less than that of Drifters.
		<br/><br/>
	The standard blood haze is caused by Drifters injuring other Drifters intentionally and with ill intent. In such a case, blood haze is triggered along with a monsterification reaction in the dealer of the damage. The severity of the reaction heavily depends on the situation. The intent, the damage, and the emotional reaction of the injured party are all factors when considering the extent of the transformation. The duration of the haze is also related to the severity, but will usually dissipate by itself when conflict in the area has been resolved.	
		<br/><br/>
	Blood Haze can also be caused by arguments, and social conflict within a group. In this case monsterification may not happen, but abominable cracks and other monstrosities may emerge. This can sometimes result in apocalyptic spirals where two Drifter groups continue to conflict until one is destroyed by the resulting Abominations. In many cases, this results in the destruction of all of the involved parties, which often transforms Abandoned Respites into heavily infested ones with Abominable Pillars and Spikes that automatically produce a vast number of Abominations. A Respite such as this can be seen as a source for the abominable cracks that open in other Abandoned Respites.
		<br/><br/>
	Monsterification reactions involve the transference of regular human body parts into disfigured, abomination-like forms. In the most severe of cases, such as murder, a Drifter can be completely transformed into an abomination of extraordinary strength. A Drifter at this point is completely unrecoverable, their mind is completely destroyed. In the more minor cases, a broken finger, sliced arm, nose, etc. A Drifter may only see monsterification of that specific body part. 	
		<br/><br/>
	Monsterification is very painful. When it begins, it starts with an immense searing pain as the skin in the area twists and contorts. In larger limbs the bones may be broken and realigned. For example, if a Drifter breaks another Drifter’s nose in an attempt to mug them, his nose will twist and contort, changing color and structure. It may turn into a very disfigured, yet still functional nose. If a Drifter cuts off another Drifter’s arm, they may find their own arm painfully morphed into a scorpion stinger, or some kind of crab pincer. While these may be useful to some, it is hardly worth the immense pain and potential risks of full monsterification.	
		<br/><br/>
	There are potentially limitless types of transformations and side effects from monsterification, as there are potentially limitless abomination forms and abilities. It is also worthy of note that an arm may not always morph into an arm. There are also cases where arms have morphed into legs, legs into arms, hands into blades, etc. 
		<br/><br/>
	Medical treatments, organized fights, and agreed upon duels will not cause blood haze unless specific guidelines have been broken. For example, if the one performing a medical treatment suddenly decides to cause actual harm, rather than help, they will be subject to blood haze. If the rules of an organized fight or duel are broken, it may also cause blood haze. For example, if someone brought in a weapon to a previously agreed upon no weapons fight, they will be subject to blood haze. There is great risk in loopholes being used in fights such as these, so it is best to be very broad and expansive with rules to prevent someone from bringing in a sword to a knife fight.
		<br/><br/>
	There are very few methods of reversing monsterification, and none of them work on fully transformed Drifters or full Abominations. One method is to simply remove the changed limb, and then use CURE to replace the lost limb. However, the shadow limb created will resemble the transformed limb, rather than the pre-transformation limb. Nonetheless, some believe it to be an improvement due to the concealment of the discolored and sometimes odorous Abomination skin. 
		<br/><br/>
		
		</font>
		]]