ITEM.name = "Blight of Light"
ITEM.desc = "A mysterious book that holds important information."
ITEM.uniqueID = "story_shade"
ITEM.model = "models/props_lab/binderbluelabel.mdl"
ITEM.price = 0
ITEM.flag = "3"
ITEM.material = "models/props_lab/security_screens2"
ITEM.contents = [[

<p align="center"><font color='black' size='6'>Blight of Light</font></p><br/>
<font color='black' size='3'>

The Walking Shadows, or the Shades, are a somewhat less common type of creature in The Void. Shades vary about as much as Aberrations, and some researchers often categorize them as a subset or a separate branch of Aberrations. 
<br/><br/>
Shades may have a variety of distinguishing features, some of which may not be present on some Shades. However, present on all Shades is a pitch black darkness covering most of their body. Some Shades may be surrounded by a black haze, or mist, which typically induces CURE-like symptoms on those who inhale it. Shades also apply this effect when physically touched by a Drifter. Most Shades are completely solid, but plenty have been observed to have more gas-like properties, some even shifting in and out of The Void.
<br/><br/>
Stronger Shades generally have incredibly powerful abilities that utilize the brain of a Drifter. These may include: mind control, mental disorientation, possession, hallucination creation, and much much more. Along with this, some may wield blighted weapons to defeat their foes. Weaker Shades are often more mindless, and will simply shamble towards their enemies, and cling to them until they are either dissolved and turned to shadow. A Shade’s abilities are not limited to these options at all, and some have been known to use things like fire, or frost instead of typical shade attacks. 
<br/><br/>
Shades are not always immediately hostile, but are easily agitated in the most fickle of ways. More powerful Shades may be intelligent, but often have no desire to have anything to do with Drifters whatsoever. A Shade may appear friendly in order to lure Drifters into a trap, or to steal CURE from them. There have been cases of Drifters sacrificing various things to Shades in order to obtain a somewhat stable peace. Along with this, some Shades have been known to offer deals to Drifters, often with a hefty price. It is unknown why Shades do this, a popular theory is that the Shades believe these deals bring Drifters closer to an end, but they do not seem to care what end it may be. Another theory is that creating tension, fear, or hatred in Drifter groups causes more CURE to arrive in the current Respite, which means the Shade can feed and grow stronger. Weaker Shades appear more mindless, and will simply wander around aimlessly.
<br/><br/>
To fight a shade is no easy task. Standard bullets will have an effect on them, but it is greatly reduced. Blighted bullets will heal Shades, and make them stronger. Shard infused weaponry is the most effective against Shades, but it can attract Abominations, and Aberrations. Shard lights are also useful, as they greatly reduce the speed at which Shades can move, and it is known to halt their phase shifting abilities, meaning they cannot easily move around the battlefield or escape. Nonetheless, Shades are known to be some of the most unpredictable and dangerous creatures in The Void, so it is necessary to have multiple backup plans in the case of fighting a powerful Shade. Even with the proper tools, properly finishing off a Shade can be very difficult. They may sacrifice body parts, hide in shadow limbs, turn into black haze, or seemingly disappear entirely, all to escape and continue existing. There is no foolproof method for destroying a Shade entirely, but harming it with shard infused weapons will significantly weaken it, which will generally force it to stay away for a significant amount of time as it regenerates. During this time it may seek easier targets, or find something else to do entirely. While Shades are incredibly dangerous, it is important to realize that the danger they present is often slow acting. A Shade will generally not attempt to kill immediately unless already provoked by shards or shard weaponry. It is best to avoid them if at all possible. 
<br/><br/>
Similar to Abominations, Shades are created and impacted by the emotions of Drifters. Weaker Shades can be produced by immense feelings of despair and hopelessness in Drifters, or by significant usage of CURE. Black haze is also notable for creating or at least attracting shades. Stronger Shades can create weaker Shades, and they often use this ability to bolster their forces in the case of a fight with well equipped Drifters. Stronger Shades are almost always created from living creatures. Most often they come from Drifters, but in rare cases they can come from Plastics as well. A Drifter’s or a Plastic’s transference to a Shade requires complete and utter despair. This is generally not an instant process, and involves a slow spiral downwards. This can often happen in the cases of sole survivors of groups, or abandonment. That being the case, many Shades are shattered personas of Drifters and Plastics who lost everything. There is no repairing a Shade, and any attempt to do so has completely failed in the past. Through this transformation, Shades generally become less human, and lose much empathy. Many Drifters are lead to their deaths by pity for the plight of a Shade. It is best to use great caution whenever dealing with a Shade’s past. Reminding a Shade of its own past may result in it going completely berserk, and attacking anything and anyone in The Respite.
<br/><br/>
</font>
]]