ITEM.name = "The Black Liquid"
ITEM.desc = "A mysterious book that holds important information."
ITEM.uniqueID = "story_cure"
ITEM.model = "models/props_lab/binderbluelabel.mdl"
ITEM.price = 0
ITEM.flag = "3"
ITEM.material = "models/props_lab/security_screens2"
ITEM.contents = [[

<p align="center"><font color='black' size='6'>The Black Liquid</font></p><br/>
<font color='black' size='3'>

CURE is a black liquid often contained in vials of plastic or glass. Typically it is very viscous. Its effects can vary depending on where and how it is used.
<br/><br/>
When CURE is utilized by a Drifter, it brings about several potentially negative effects.
The Drifter will first become numb throughout their body, the largest degree of which will depend on where and how it is applied. Drinking the liquid numbs the entire body equally, and the numbing effects are also almost instantaneous. For an average adult male, one vial is sufficient to numb the entire body moderately. This numbing effect’s duration depends largely upon how much CURE was used, and whether it was consumed or applied topically. Consuming the liquid will have double the duration of applying it topically. Generally, an entire vial of cure applied topically will numb someone for at least an hour.
<br/><br/>
After the body has become numb, the Drifter will experience some sort of nostalgic memory overflow. where they are essentially overwhelmed with thoughts and memories of their own pasts from before they entered The Void. This mental state often leaves those afflicted in a somewhat absentminded state. Along with that, they may sometimes experience hallucinations, which make them especially vulnerable to any danger around them. The hallucinations are often memory-like visions of their own pasts, they may see people they knew like family members or friends. It is very difficult for a Drifter in this state to tell the difference between the hallucination and world around them. This effect will last as long as the numbness will.
<br/><br/>
CURE has vital medical uses that should not be overlooked. Even when considering the dangers of using CURE, it is by far the most reliable way for a Drifter to save the life of another in the case of life threatening injuries. Upon applying CURE topically or orally, injuries sustained on the body will be replaced with a blackened substance often simply referred to as “shadow.” This essentially nullifies the injury, stopping bleeding, fixing bones, and repairing tissue. It can even replace entire organs. However, shadow body parts have significant disadvantages when compared to a standard one. The most obvious downside is that they are constantly numb. This numbness makes them more difficult to control, but this also makes them somewhat more resistant to pain. Those with shadow fingers may find it difficult to play an instrument, or properly aim a firearm. Those with shadow legs or feet may find themselves running or moving slower. These disabilities also apply to shadow organs, which can lead to those with shadow hearts having fairly low blood pressure. The other major downside of shadow body parts, is the risk of “shadowification.” Shadowification is the process of a Drifter’s entire body turning into shadow material. This generally happens as a result of CURE overuse, having too many shadow body parts, or the brain tissue being replaced with shadow.
<br/><br/>
As state before, CURE does not heal wounds in a traditional fashion. CURE has properties of reversal and destruction. In the case of Drifters, it generally reverses. Using it on an injury will reverse the injury back to a previous state, when the injury did not exist. However, this process comes with the cost of sending part of the body part back to The Faux. This is the primary cause of the numbness experienced with shadow body parts. If a shard is in contact with a numbed shadow body part, it will return feeling to that part so long as it continues to make contact with it. For some the body parts also regain their natural color and texture as well, but this depends on the person, and is seemingly random. The reason Shards have this effect, is because Shards return the body part from The Faux temporarily, essentially tying it down to The Void. If the Shard is removed from physical contact for even a second, the shadow body part will return to shadow. Shards cannot bring someone back if they have entirely gone shadow. They are fully in The Void, and such measures are insufficient.
<br/><br/>
CURE is often noted to be a powerful reversal agent, and is used in various machines and devices to produce these effects. That being the case, it is specifically good at reducing or converting objects into more base materials. Specific devices of note are the Salvager Kit and the Sacrificial Skull. This trait also makes CURE a lethal weapon against non-Drifter entities. Against most creatures, it will dissolve their bodies quite easily, as if it were a strong acid. CURE soaked bullets and spraying hoses are effective weapons against Abominations, Aberrations, Plastics, and Fiends. However, using these weapons against Shades, or other Faux tainted beings, will only serve to make them more powerful. It is also advised to limit the use of CURE as a weapon, as gratuitous use will attract Shades and other Shadow creatures.
<br/><br/>
One notable case of excessive CURE weaponry was Respite #7192. There was a large battle involving unprecedented amounts of Abominations over the course of multiple days. Fearing the overwhelming force, the Drifters and Plastics in the area were forced to use anything they could get their hands on, this included CURE sprayers, CURE enhanced weaponry, CURE bullets, and blighted flamethrowers. The aftermath of the gruesome battle left large pools of CURE all over the surface of 7192. There was no place unmarked, even in the significantly sized world. Eventually, the Respite itself began to rot away entirely, the ground fell away, walls crumbled, and the sky turned black. Drifters that were in the area slowly experienced shadowification, and even Drifters who were no longer in the area slowly succumbed to it as well. It also resulted in what has come to be known as the “Shadow Poison” disease, which slowly transforms a Drifter into a shadow starting at one of their limbs. The disease can be treated by purging the shadow from the body with a shard, or a shard infused object. However, in purging the disease, it leaves the current host’s body, and seemingly attempts to find a new one, as if it were a living being. To truly destroy a case of this disease, a fake body must be prepared for the disease to spread to. Once it has spread to the fake body, it will become blackened, and then slowly disappear. The disease is also mildly infectious, usually prolonged physical contact with blackened body parts is the only way for it to spread outside of the purge transferring described previously. It is currently unknown what the current state of Respite #7192 is, as there have been no reports of anyone ever seeing such a place since the disastrous events took place. Nonetheless, its legacy lives on in stories and the ancient blighted weapons that rarely find their way into a Drifter’s hands.
<br/><br/>
</font>
]]