ITEM.name = "Drifters"
ITEM.desc = "A mysterious book that holds important information."
ITEM.uniqueID = "story_drifter"
ITEM.model = "models/props_lab/binderbluelabel.mdl"
ITEM.price = 0
ITEM.flag = "3"
ITEM.material = "models/props_lab/security_screens2"
ITEM.contents = [[

<p align="center"><font color='gray' size='6'>Drifters</font></p>
<font color='black' size='3'>
<br/>
In The Void, humans are referred to as Drifters. The reason for this particular name is due to their somewhat nomadic state in regards to Respites. Most often do not stay in one single Respite, but move through multiple throughout their lives. Drifters have many reasons to do this, but it is often personal and can vary from Drifter to Drifter. Some are searching for a way out, while others are searching for a new place to call home.
<br/><br/>
Drifters are unique in that they are never created, they all come from The Faux. Generally after entering The Void, a Drifter will be very confused, and vulnerable. Fortunately, new Drifters almost always enter The Void in Respites that already have a decent Drifter presence, meaning that not many are immediately thrown to the wolves. However, this does still happen from time to time. Drifters that survive alone are considered to be quite skilled and knowledgeable, some Drifter groups take to hiring them for more dangerous expeditions or to accomplish certain dangerous objectives.
<br/><br/>
Drifters, with their strengths and numbers, are considered to be one of the strongest forces throughout The Void. It is commonly said that if all Drifters were to unite, they could easily conquer all of the Abandoned Respites in The Void. However, due to the chaotic nature of The Void, and the seemingly infinite number of Abandoned Respites, this is likely an exaggeration of both power and ability. Nonetheless, the power of Drifters is not to be underestimated by any regard. Drifters are responsible for destroying a number of seemingly impossibly strong threats, even creatures that many would consider as having god-like powers. Drifters are known to overcome all odds to survive, even when fighting against impossible odds and completely unfair powers. 
<br/><br/>
The most significant of the Drifters’ powers is the both conscious and unconscious ability to create. The mind of a Drifter has an immense impact on the Respite they are housed within, especially if that Respite is their own. The emotions and mental state of Drifters in an area passively create Abominations, Aberrations, and sometimes Shades. They can also impact the weather, and bring about other anomalous events. Blood Haze is a very common example of this. Drifters are also able to actively create Plastics that will obey and follow them, they can even train Abominations and Aberrations given the proper resources and time. Drifters are also the only known creatures to be able to create Respites, and remarkably easily as well. For more information see: “Respites”.
<br/><br/>
The Drifters’ ability to create can also occasionally be directed towards their own or other Drifters’ bodies. This is most commonly observed in Blood Haze mutations, but there are also less common occurrences of Drifters turning into Aberrations, Plastics, and Shades as well. The malleable state of a Drifter’s body is not limited to full transformations, and small changes in their body can happen over time. Drifters may accumulate shadowy body parts, or have entire sections of their body replaced with Abomination flesh. It is rare to see an experienced Drifter without some sort of difference from regular human biology, and it is an important part of Drifter health to avoid more transformations whenever possible, for if the brain of a Drifter is transformed, the creature ceases to be a Drifter, and becomes something else entirely. If the Drifter’s mind is transformed, it is likely that the new creature will not retain the memories or personality of the Drifter it came from. However, there are special cases where seemingly full transformations happen, and the Drifter’s mind is left intact. This can happen with some Aberration transformations, and even some Plastic ones. Shades generally retain the memories of the Drifter before them, but they often become distorted and twisted, resulting in a being that somewhat resembles who it once was, but not quite. In the case of a full Abomination transformation, no part of who the Drifter once was ever survives and the mind is completely destroyed. Unfortunately, once a transformation of occurred, it is seemingly impossible to return the creature back to a Drifter. No attempts to do so have ever succeeded.
<br/><br/>
A transformed Drifter is often fairly powerful right after creation, they are generally tougher, faster, and stronger than a typical creature, but that can vary. There does not seem to be any correlation between the Drifter’s strength before and after transformation. A strong Drifter may turn into a weak Abomination. A weak Drifter may transform into a truly monstrous Aberration or Abomination. The true power of a transformed Drifter is not immediately after the transformation. Creatures such as these are capable of growing in power, and can become very dangerous if not dealt with quickly. Plasticized Drifters may create and rally massive armies. Abominable and Aberrative Drifters may grow and mutate further, developing new abilities or shedding weaknesses. Drifter Shades may rapidly absorb other Shades, and develop very concerning abilities if left unchecked. 
<br/><br/>
Drifter colonies rise and fall just like any other, but they do tend to last longer than those of Plastics. There are some historical records referring to ancient Drifter colonies, ones that supposedly flourished for hundreds if not thousands of years. However, there have been no witness accounts of finding any such place. That being the case, it is believed that if these places exist, they are likely not in Abandoned Respites, but in a Drifter’s own Respite room. Such places are generally safer with less Abominations and Aberrations. This would explain why some recently Abandoned Respites have massive ruins and demolished cities. However, this theory lacks an explanation for how the mental state of the Drifter can survive for so long with such a thing affecting their mind, especially with multiple Drifters living within. 
<br/><br/>
Drifters use a variety of devices and tools, both those of real world origin, and those of Void origin. Most obvious for most is the Vending Machine, Fabricator, and Respite Box. These devices typically appear around Drifter groups of no less than five, and seemingly appear somewhere in whatever Abandoned Respite they enter. These devices generally create a convenient area for Drifters to congregate around due to their various uses, which leads to them becoming the heart of any Drifter encampment. Drifters also make use of other various devices, such as the generator, the farms, refineries, and portal devices. Some Drifters even take to invent new tools and devices. These devices are often given to the Fabricator, which allows Drifters and Plastics in other Respites to make use of them provided they have the materials necessary to create them.
<br/><br/>
New Drifters typically have completely human biology, but there are some differences and important traits to note. <br/>
Drifters tend to be at least eighteen years of age, but younger than eighty. <br/>
Drifters can eat anything that a human can, but it is not uncommon for a Drifter to mutate in a way that allows or prohibits certain meals. <br/>
Drifters cannot become pregnant or give birth in The Void. It is unknown why exactly this is the case, but it seems to stem from the fact that new Drifters cannot be created by other Drifters under any circumstances. Furthermore, the effects of sexual intercourse appear to be poorly understood within The Void. It is known that Drifters have an immense effect on their environment with their mental status. Thus, one would assume that intercourse would as well, due to the emotional impact of such a thing. However, no data currently exists that provides a link to what impact it might have at all. Most believe that something is impacted, but there is no indication of what that might be.<br/>
Drifters do not age normally, and will always appear to be the same age unless acted upon by an outside force, such as an Aberration with time altering abilities. This means that Drifters, unless killed or altered somehow, can potentially live forever, in theory.
<br/><br/>
Typically a Drifter will undergo a variety of changes throughout their lives. As described before, there are many potential transformations that a Drifter can obtain. The Drifter may also experience other miscellaneous changes due to encounters while in The Void. There are cases of Drifters looking stranger than Aberrations, and more disturbing than Abominations. Thus, it is important to exercise caution if there is any doubt of a creature’s true identity, otherwise a Blood Haze reaction could be triggered. 
</font>
]]