ITEM.name = "Blighted Past"
ITEM.desc = "A mysterious book that holds important information."
ITEM.uniqueID = "story_blight"
ITEM.model = "models/props_lab/binderbluelabel.mdl"
ITEM.material = "models/props_lab/security_screens2"
ITEM.price = 0
ITEM.flag = "3"
ITEM.category = "Lore"

ITEM.iconCam = {
	pos = Vector(0, 200, 6),
	ang = Angle(0, 270, 0),
	fov = 4.5,
}

ITEM.contents = [[

<p align="center"><font color='black' size='6'>Blighted Past</font></p><br/>
<font color='black' size='3'>

Blight is a black liquid often contained in vials of plastic or glass. Typically it is very viscous. Its effects can vary depending on where and how it is used. The most common use by drifters is to increase the damage of weapons towards abominations, aberrations, plastics, and fiends.
	<br/><br/>
When blight is utilized by a drifter, it brings about several potentially negative effects. The drifter will first become numb throughout their body, the largest degree of which will depend on where and how it is applied. Drinking the liquid numbs the entire body equally, and the numbing effects are also almost instantaneous. For an average adult male, one vial is sufficient to numb the entire body moderately. This numbing effect’s duration depends largely upon how much blight was used, and whether it was consumed or applied topically. Consuming the liquid will have double the duration of applying it topically. Generally, an entire vial of cure applied topically will numb someone for at least an hour.
	<br/><br/>
After the body has become numb, the drifter will experience some sort of nostalgic memory overflow. where they are essentially overwhelmed with thoughts and memories of their own pasts from before they entered the Void. This mental state often leaves those afflicted in a somewhat absent minded state. Along with that, they may sometimes experience hallucinations, which makes them especially vulnerable to any danger around them. The hallucinations are often memory-like visions of their own pasts, they may see people they knew like family members or friends. It is very difficult for a drifter in this state to tell the difference between the hallucination and world around them. This effect will last as long as the numbness will.
	<br/><br/>
Blight has notable medical uses that should not be overlooked. Even when considering the dangers of using blight, it is by far the most reliable way for a drifter to save the life of another in the case of life threatening injuries. Upon applying blight topically or orally, injuries sustained on the body will be replaced with a blackened substance often simply referred to as “shadow.” This essentially nullifies the injury, stopping bleeding, fixing bones, and repairing tissue. It can even replace entire organs. However, shadow body parts have significant disadvantages when compared to a standard one. The most obvious downside is that they are constantly numb. This numbness makes them more difficult to control, but this also makes them slightly more resistant to pain. Those with shadow fingers may find it difficult to play an instrument, or properly aim a firearm. Those with shadow legs or feet may find themselves running or moving slower. These disabilities also apply to shadow organs, which can lead to those with shadow hearts having fairly low blood pressure. The other major downside of shadow body parts, is the risk of “shadowification.” Shadowification is the process of a drifter’s entire body turning into shadow material. This generally happens as a result of blight overuse, having too many shadow body parts, or the brain tissue being replaced with shadow. When this happens, the Drifter will solidify as a “Shadow Statue”, and become a haunting reminder of the danger of blight.
	<br/><br/>
As state before, blight does not heal wounds in a traditional fashion. Blight essentially reverses the injury, rather than healing it conventionally. This is thought of to be related to its connections to the past, and The Faux. Simply put, using it on an injury will revert the injury back to a previous state, when the injury did not exist. However, this process comes with the cost of sending part of the body part back to The Faux. This is the primary cause of the numbness experienced with shadow body parts. If a shard is in contact with a numbed shadow body part, it will return feeling to that part so long as it continues to make contact with it. For some the body parts also regain their natural color and texture as well, but this depends on the person, and is seemingly random. The reason shards have this effect, is because shards return the body part from The Faux temporarily, essentially pulling it back into The Void. If the shard is removed from physical contact for even a second, the shadow body part will return to shadow. Shards cannot restore those that have become shadow statues, as they have completely entered The Faux.
	<br/><br/>
Blight is often noted to be a powerful reversal agent, and is used in various machines and devices to produce these effects. That being the case, it is effective at reducing or converting objects into more base materials. Specific devices of note are the Salvager Kit and the Sacrificial Skull. This trait also makes blight a lethal weapon against a fair amount of creatures. Against Abominations and Aberrations, it will dissolve their bodies like a powerful acid. Against fiends and plastic, it will harden their skin, and make it fragile. This is generally the source of most mannequins. These effects make blight soaked bullets and spraying hoses very effective weapons in a variety of situations. However, using these weapons against shades will only serve to make them more powerful. It is also advised to limit the use of blight as a weapon, as gratuitous use will attract, or sometimes even create shades. It is also wise to avoid caution using blight against wraiths as well, as ichor and blight combining typically causes a large, dangerous shockwave. While effective at destroying wraiths, it is also effective at destroying everything around the wraiths.
	<br/><br/>
One notable case of excessive blight weaponry was Respite #7192. Known as the respite of eternal battle, those within the area began to employ vast amounts of blight based weaponry to finally put an end to the looming abomination hordes. The powerful, and experimental weapons were successful at destroying the various abomination pillars and forces, but had an unwelcome side effect of significantly decreasing the stability of the respite. The vast pools of blight remaining across the various battlefields drew in an unheard of amount of shades, and eventually the area was overcome entirely. The respite itself also became dangerous to just be inside of. The drifters and plastics in the area became to slowly show signs of blight. The plastics began to harden into mannequins, and the drifters slowly turned into shadow statues. Those that fled found themselves afflicted with a dangerous disease known as the shadow plague, which likely killed most of, if not all of the survivors. The respite itself could not be travelled to by any means for quite some time, though some drifters reported interactions with objects or entities from the area, but there was little evidence substantiating these claims. This case is a grim reminder of the dangerous capabilities of blight.
	<br/><br/>

</font>
]]