ITEM.name = "Haze of War"
ITEM.desc = "A mysterious book that holds important information."
ITEM.uniqueID = "story_haze_blood"
ITEM.model = "models/props_lab/binderbluelabel.mdl"
ITEM.material = "models/props_lab/security_screens2"
ITEM.price = 0
ITEM.flag = "3"
ITEM.category = "Lore"

ITEM.iconCam = {
	pos = Vector(0, 200, 6),
	ang = Angle(0, 270, 0),
	fov = 4.5,
}

ITEM.contents = [[

<p align="center"><font color='red' size='6'>Haze of War</font></p><br/>
<font color='black' size='3'>
		
Blood haze is a term that can refer to a reaction incurred when drifters fight one another, or it can refer to the weather anomaly that occurs shortly after such events.
	<br/><br/>
During a blood haze situation, all of the following will occur. The sky will turn a deep blood red, and a thick red fog will rapidly fill the area. Visibility will be reduced substantially by the shifting fog, and abominations will emerge all over the respite. Those who are exposed to blood haze for long periods of time may find themselves angrier, or furious for no particular reason. Abominations during haze will fight more ferociously than normal, and sometimes even be more durable. To avoid injury or death in such a situation, it is best to move indoors for a better position with less blind spots.
	<br/><br/>
The fog generated by blood haze is primarily composed of abomination blood, and very rarely, fiend blood. This blood can fall from the sky as rain, or simply drift about as haze. Regardless, it will end up in the environment in one way, or another. In extreme cases, everything left outside may end up covered in blood before the end of the storm, making a disgusting and difficult to traverse environment. The haze also has the effect of exciting and enraging abominations in the area, this is thought to be due to the unavoidable smell. This scent appears to be the primary reason for the increased strength of abominations during the haze.
	<br/><br/>
Geological events called “cracks” are commonly witnessed during blood haze. Such cracks appear to be glowing red openings in the ground, walls, or ceiling. These cracks are often jagged and crude, a seemingly different form of portal than most others seen in the Void. From these cracks, abominations will emerge and immediately attack anyone or anything nearby. The larger the crack, typically the larger the abominations, or the larger the number of abominations. The duration of a crack may last anywhere from a few seconds, to until the blood haze ends. It is possible to fall into a crack as well, and those that have ended up finding themselves falling through what was described by one drifter as “a vision worse than hell” before being shot out somewhere else in the respite.
	<br/><br/>
The underlying reason for most of the blood haze reactions is the conflict between drifters. This is usually in the form of physical violence, but in some cases arguments or emotional damage can cause it as well. Excess abomination activity as well as cases of extreme violence by other intelligent creatures can also bring about the blood haze. The reason for this seems to be related to the effects of consciousnesses on abandoned respites. Every thought and emotion has the slight potential of creating something within a respite, and in situations of conflict or disaster, this effect is amplified, resulting in dangerous situations created in the worst possible times.
	<br/><br/>
The standard blood haze reaction is caused by drifters injuring other drifters intentionally and with ill intent. In such a case, a monsterification backlash will also come with the actual haze. A monsterification backlash involves the mutation of some part of the attacking drifter’s body into something more similar to an abomination. The severity of the monsterification reaction heavily depends on the situation. The intent, the damage, and the emotional reaction of the injured party are all factors that can amplify the extent of the mutation. The duration of the haze is also related to the severity, but will usually dissipate by itself when conflict in the area has been resolved.
	<br/><br/>
In the case of blood haze caused by social conflicts, monsterification may not always happen, but all the actual haze and cracks will likely still occur. This can sometimes result in apocalyptic spirals where two Drifter groups continue to conflict until one or both are destroyed by the resulting abominations. This sometimes results in the destruction of all of the involved parties, which transforms respites into abomination “nests” of sorts, where pillars and abomination producing structures are common. Respites such as these are likely the other side of the cracks that form during these reactions.
	<br/><br/>
Monsterification reactions involve the transference of regular human body parts into disfigured, abomination-like forms. In the most severe of cases, such as murder, a drifter can be completely transformed into an abomination of extraordinary strength. A drifter at this point is completely unrecoverable, their mind is completely destroyed. In the more minor cases, a broken finger, sliced arm, nose, etc. A drifter may only see monsterification of that specific body part. 
	<br/><br/>
Monsterification is very painful. When it begins, it starts with an immense searing pain as the skin in the area twists and contorts. In larger limbs, the bones may be broken and realigned. For example, if a drifter breaks another drifter’s nose, the attacker’s nose will seemingly break by itself, twist, morph, and realign itself. It will change color and structure until it has arrived at a more horrid appearance. If a Drifter cuts off another Drifter’s arm, they may find their own arm painfully morphed into a scorpion stinger, or some kind of crab pincer. These mutated body parts are usually still functional for the most part, they can be more painful to manipulate for quite some time after the initial transformation.
	<br/><br/>
There are potentially limitless types of transformations and side effects from monsterification, as there are potentially limitless abomination forms and abilities. It is also worthy of note that an arm may not always morph into an arm. There are also cases where arms have morphed into legs, legs into arms, hands into blades, etc. 
	<br/><br/>
Medical treatments, organized fights, and agreed upon duels will not cause blood haze unless specific guidelines have been broken. For example, if the one performing a medical treatment suddenly decides to cause actual harm, rather than help, blood haze is very likely to occur. If the rules of an organized fight or duel are broken, it may also cause blood haze. If someone brings a weapon to a previously agreed upon no weapons fight, they will also most likely cause blood haze. There is great risk in loopholes being used in fights such as these, so it is best to be very precise with rules to prevent someone from bringing a sword to a knife fight.
	<br/><br/>
There are very few methods of reversing monsterification, and none of them work on fully transformed drifters or full abominations. One method is to simply remove the changed limb, and then replace it with a prosthetic or mechanical limb, but this is hardly a cure. Further methods are still being researched, but be wary of any remedies that promise results immediately, especially from those of suspicious character.
	<br/><br/>	
		
</font>
]]