ITEM.name = "Converter - Organic"
ITEM.uniqueID = "converter_meat"
ITEM.desc = "A peculiar tool with a climb and a lever."
ITEM.model = "models/props_c17/grinderclamp01a.mdl"
ITEM.material = "models/flesh"
ITEM.flag = "v"
ITEM.height = 2
ITEM.category = "Machines"
ITEM.color = Color(255, 50, 50)