ITEM.name = "Firing Mechanism"
ITEM.uniqueID = "comp_firing_mechanism"
ITEM.model = "models/warz/items/syringe.mdl"
ITEM.desc = "A makeshift firing mechanism useful for creating simple weaponry."
ITEM.flag = "v"
ITEM.price = 10
ITEM.width = 1
ITEM.height = 1
ITEM.material = "models/props_wasteland/quarryobjects01"