ITEM.name = "Intrinsic Symbol"
ITEM.uniqueID = "chip_escape"
ITEM.desc = "A small rectangular object, it is the same size as a regular or enhanced chip.\nThe chip vibrates lightly, and you can feel a slight heat coming from within.\nOnly Drifters and some Shades can perceive this object.\nThis chip seems incredibly important somehow."
ITEM.model = "models/gibs/metal_gib4.mdl"
ITEM.material = "models/props_combine/stasisfield_beam"
ITEM.flag = "v"
ITEM.category = "Machines"